** Cleaning and preparing the data for model training

In [4]:
pip install pandas

Collecting pandasNote: you may need to restart the kernel to use updated packages.

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\aboyc\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: You are using pip version 21.2.3; however, version 26.1.1 is available.
You should consider upgrading via the 'c:\Users\aboyc\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

  Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
Collecting numpy>=1.22.4
  Downloading numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aboyc\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1
  Downloading pytz-2026.2-py2.py3-none-any.whl (510 kB)
Collecting tzdata>=2022.7
  Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Requirement already satisfied: six>=1.5 in c:\users\aboyc\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: tzdata, pytz, numpy, pandas
Successfully installed numpy-2.2.6 pandas-2.3.3 pytz-2026.2 tzdata-2026.2

In [6]:
pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.10.9-cp310-cp310-win_amd64.whl (8.2 MB)
Collecting pyparsing>=3
  Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Collecting cycler>=0.10
  Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Requirement already satisfied: numpy>=1.23 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (2.2.6)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\aboyc\appdata\roaming\python\python310\site-packages (from matplotlib) (2.9.0.post0)
Collecting pillow>=8
  Downloading pillow-12.2.0-cp310-cp310-win_amd64.whl (7.1 MB)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.63.0-cp310-cp310-win_amd64.whl (1.6 MB)
Requirement already satisfied: packaging>=20.0 in c:\users\aboyc\appdata\roaming\python\python310\site-packages (from matplotlib) (26.2)
Collecting kiwisolver>=1.3.1
  Downloading kiwisolver-1.5.0-cp310-cp310-win_amd64.whl (73 kB)
Collecting contourpy>=1.0.1
  Downloading contourpy-1.3.2-cp310-cp310-win_amd64.whl (221 kB)
Requirement already satisfied: six>=1.5 in c:\users\aboyc\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
Successfully installed contourpy-1.3.2 cycler-0.12.1 fonttools-4.63.0 kiwisolver-1.5.0 matplotlib-3.10.9 pillow-12.2.0 pyparsing-3.3.2
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'c:\Users\aboyc\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: You are using pip version 21.2.3; however, version 26.1.1 is available.
You should consider upgrading via the 'c:\Users\aboyc\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [8]:
pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Requirement already satisfied: pandas>=1.2 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from seaborn) (3.10.9)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from seaborn) (2.2.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\aboyc\appdata\roaming\python\python310\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: cycler>=0.10 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: packaging>=20.0 in c:\users\aboyc\appdata\roaming\python\python310\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: pillow>=8 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\aboyc\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 26.1.1 is available.
You should consider upgrading via the 'c:\Users\aboyc\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [11]:
df_train = pd.read_csv(r'C:\Users\aboyc\EDA\archive (12)\train.csv')
df_train.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969

In [13]:
df_test = pd.read_csv(r'C:\Users\aboyc\EDA\archive (12)\test.csv')
df_test.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
0,1000004,P00128942,M,46-50,7,B,2,1,1,11.0,NaN
1,1000009,P00113442,M,26-35,17,C,0,0,3,5.0,NaN
2,1000010,P00288442,F,36-45,1,B,4+,1,5,14.0,NaN
3,1000010,P00145342,F,36-45,1,B,4+,1,4,9.0,NaN
4,1000011,P00053842,F,26-35,1,C,1,0,4,5.0,12.0

In [ ]:
df = pd.concat([df_train,df_test], ignore_index=True)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 783667 entries, 0 to 783666
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     783667 non-null  int64
 1   Product_ID                  783667 non-null  object
 2   Gender                      783667 non-null  object
 3   Age                         783667 non-null  object
 4   Occupation                  783667 non-null  int64
 5   City_Category               783667 non-null  object
 6   Stay_In_Current_City_Years  783667 non-null  object
 7   Marital_Status              783667 non-null  int64
 8   Product_Category_1          783667 non-null  int64
 9   Product_Category_2          537685 non-null  float64
 10  Product_Category_3          237858 non-null  float64
 11  Purchase                    550068 non-null  float64
dtypes: float64(3), int64(4), object(5)
memory usage: 71.7+ MB

In [19]:
df.describe()

,User_ID,Occupation,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
count,7.836670e+05,783667.000000,783667.000000,783667.000000,537685.000000,237858.000000,550068.000000
mean,1.003029e+06,8.079300,0.409777,5.366196,9.844506,12.668605,9263.968713
std,1.727267e+03,6.522206,0.491793,3.878160,5.089093,4.125510,5023.065394
min,1.000001e+06,0.000000,0.000000,1.000000,2.000000,3.000000,12.000000
25%,1.001519e+06,2.000000,0.000000,1.000000,5.000000,9.000000,5823.000000
50%,1.003075e+06,7.000000,0.000000,5.000000,9.000000,14.000000,8047.000000
75%,1.004478e+06,14.000000,1.000000,8.000000,15.000000,16.000000,12054.000000
max,1.006040e+06,20.000000,1.000000,20.000000,18.000000,18.000000,23961.000000

In [20]:
df.drop(['User_ID'],axis =1, inplace = True)

In [21]:
df.head()

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370.0
1,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200.0
2,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422.0
3,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057.0
4,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969.0